
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-14T21:20:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "87389e4befb035415282fd00f2b8c63f0502845e",
 "version": "0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)

